language: python
python:
  - 3.7

# Build matrix: Run different versions of GCC and tests in parallel
jobs:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - ninja-build
            - gfortran-7
            - python-pip
      env:
        - FC=gfortran-7

    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - ninja-build
            - gfortran-8
            - python-pip
      env:
        - FC=gfortran-8

install:
  - pip3 install meson fypp

script:
  - meson build --buildtype=release && ninja -C build
