set(CMAKE_IMPORT_FILE_VERSION 1)

set(
  TOMLF_INCLUDEDIRS
  "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@"
  "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@/@module-dir@"
)
find_library(
  TOMLF_LIBRARIES
  "@PROJECT_NAME@"
  PATHS "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@"
  NO_DEFAULT_PATH
)

add_library(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE IMPORTED)
add_library(@PROJECT_NAME@::@PROJECT_NAME@ ALIAS @PROJECT_NAME@::@PROJECT_NAME@-lib)
target_link_libraries(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE ${TOMLF_LIBRARIES})
target_include_directories(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE ${TOMLF_INCLUDEDIRS})
